# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89e622a8419e176d181a20b4f72886c3c366ae4341389fd94c4e9a1fbdeea2c9fff32aaecea2c2f162aebbe32482740a01415defa637f07468bf1bf2838fceb3

test:
  secret_key_base: bee6b0ea036c13fd1fd73affa5203b4bf54ee64d874188fe65705e074f6ef72bd5f4c067350a2d94f00ef69f8a222b7073c0803b6cc082f262428bf39815e0f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
